#!/bin/bash
cd $(dirname "$0")
clear
export NAME=$(basename $(pwd))
export VERSION=$(head -n 1 version.txt | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

if [ -f "$NAME.g3a" ]; then
    rm "$NAME.g3a"
fi

make

if [ -d "build" ]; then
    rm -rf build
    if [ -f "$NAME.bin" ]; then
        rm "$NAME.bin"
    fi
fi
